### ISSUE TITLE
AttributeError: 'RandomForestQuantileRegressor' object has no attribute '_validate_data' (sklearn 1.6)

### ISSUE THREAD

**Issue by TamaraAtanasoska** [zillow/quantile-forest#103]
Hi! I am working on updating `skops` to work with `sklearn 1.6`. 
One of the issues is that some of the 'RandomForestQuantileRegressor' with the following error for these lines([one](https://github.com/zillow/quantile-forest/blob/main/quantile_forest/_quantile_forest.py#L135), [two](https://github.com/zillow/quantile-forest/blob/cb622f33f0b90fdf6355dcd22d28a530e584070f/quantile_forest/_quantile_forest.py#L819)):

`AttributeError: 'RandomForestQuantileRegressor' object has no attribute '_validate_data'. Did you mean: '_validate_params'?`

I also notice `force_all_finite` in the file, which [will be deprecated](https://github.com/scikit-learn/scikit-learn/blob/7387c267e4c57de2ffd118ca9df85576b01df11c/sklearn/utils/validation.py#L818). Not a problem for `skops` atm, but an added potential `sklearn 1.6` compatibility issue.

Thanks in advance for looking into this!

**Comment by reidjohnson** [comment]
Thanks so much for the heads up on this, @TamaraAtanasoska! The current compatibility issues with sklearn 1.6 have been resolved in main and will be included in the next release.
